services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    container_name: softy-pinko-back-end

  front-end:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./softy-pinko-front-end:/var/www/html/softy-pinko-front-end
      - ./softy-pinko-front-end.conf:/etc/nginx/conf.d/default.conf
    container_name: softy-pinko-front-end
    depends_on:
      - back-end
