services:
  back-end:
    build:
      context: .
      dockerfile: softy-pinko-back-end/Dockerfile
    ports:
      - "5252:5252"
    
  front-end:
    build:
      context: .
      dockerfile: softy-pinko-front-end/Dockerfile
    ports:
      - "80:80"
