services:
  front-end:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - front-end

  back-end-1:
    build: .
    environment:
      - PORT=5252

  back-end-2:
    build: .
    environment:
      - PORT=5253
