services:
  front-end:
    build: ./softy-pinko-front-end
    ports:
      - "9000:80"

  back-end:
    build: ./softy-pinko-back-end
    ports:
      - "5252:5252"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end