services:
  back-end:
    build: .
    ports:
      - "5252:5252"
    depends_on:
      - db

  front-end:
    build: ./softy-pinko-front-end
    ports:
      - "9000:80"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end