services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  front-end:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./softy-pinko-front-end:/var/www/html/softy-pinko-front-end
      - ./softy-pinko-front-end.conf:/etc/nginx/conf.d/default.conf
    container_name: softy-pinko-front-end

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
